### ISSUE TITLE
Missing 'TargetFramework' property should not cause an Exception

### ISSUE THREAD

**Issue by synek317** [nunit/vs-project-loader#37]
Becuase of this line, if any csproj inside a solution uses `<TargetFrameworks>` instead of `<TargetFramework>`, running nunit3-consolle on whole solution raises an exception:

```
string targetFramework = _doc.SelectSingleNode("Project/PropertyGroup/TargetFramework").InnerText;
```

I'm not sure if the project is maintained or not but I believe the fix is pretty easy and seeing it fixed would really help.

**Comment by CharliePoole** [comment]
@synek317 I'm closing this as fixed, although all I have actually done is add at test that shows it works as designed. It's possible that some other change since the last release fixed it. But it's also possible that I've missed something. :-(

Can you try out the build with the fix from https://www.myget.org/feed/nunit/package/nuget/NUnit.Extension.VSProjectLoader/3.9.0-dev00047 (nuget) or https://www.myget.org/feed/nunit/package/nuget/nunit-extension-vs-project-loader/3.9.0-dev00047 (chocolatey) and let me know how it works for you? If it still doesn't work, we can reopen this.

A note about expectations:

To NUnit, the config is simply "Debug" or "Release" (or some other config name) When you run your solution using one of them (or the default) you should see your tests run for all three platforms, using the proper output paths. The console runner has no way to select a particular platform, so the extension doesn't support it either.

**Comment by CharliePoole** [comment]
This is fixed in the sense that you may now use TargetFrameworks rather than TargetFramework. However, only one runtime is actually supported. I did it this way because this fix is trivial and multiple runtime support will take more time. You can follow progress on multiple runtimes on issue #26
